# Generated by Django 4.0.4 on 2022-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Tittle', models.CharField(max_length=50)),
                ('Blog_Time', models.DateTimeField(auto_now=True)),
                ('Blog_Description', models.CharField(max_length=350)),
                ('Blog_AuthorName', models.CharField(max_length=30)),
            ],
        ),
    ]
